name: iconoir_icons
description: Iconoir set of SVG icons in your Flutter app.
version: 0.1.1
repository: https://github.com/gendaineko2222/iconoir_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  path: ^1.8.2

dev_dependencies:
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  recase: ^4.0.0

flutter:
  assets:
    - assets/
